name: Build and deploy Storybook
on: 
  push:
    branches:
      - '**'
  pull_request:
      branches:
        - 'main'
env:
  PIA_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN_PIA }}
  AA_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN_AA }}
jobs:
  deploy-storybooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
      - name: Build PIA Storybook
        run: npx nx run portal-integration-angular:build-storybook
      - name: Check PIA Chromatic token
        if: env.PIA_TOKEN == null
        run: echo "PIA_TOKEN missing. Skipping Chromatic deployment for Portal Integration Angular."
      - name: Check Angular Accelerator Chromatic token
        if: env.AA_TOKEN == null
        run: echo "AA_TOKEN missing. Skipping Chromatic deployment for Angular Accelerator."
      - name: Publish to PIA Chromatic
        uses: chromaui/action@latest
        if: env.PIA_TOKEN != null
        with:
          projectToken: ${{ env.PIA_TOKEN }}
          storybookBuildDir: dist/storybook/portal-integration-angular
          skip: 'dependabot/**'
      - name: Build AA Storybook
        run: npx nx run angular-accelerator:build-storybook
      - name: Publish to AA Chromatic
        uses: chromaui/action@latest
        if: env.AA_TOKEN != null
        with:
          projectToken: ${{ env.AA_TOKEN }}
          storybookBuildDir: dist/storybook/angular-accelerator
          skip: 'dependabot/**'
